name: lipread
description: "An app to assist learning lip-reading for the hearing impairments"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dotted_line: ^3.2.2
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2
  video_player: ^2.8.1
  http: ^1.1.0
  provider: ^6.1.1
  record: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
  fonts:
    - family: pretendard
      fonts:
        - asset: fonts/PretendardVariable.ttf
    - family: bronova
      fonts:
        - asset: fonts/Bronova-Bold.ttf
