name: lipread
description: "An app to assist learning lip-reading for the hearing impairments"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dotted_line: ^3.2.2
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2
  video_player: ^2.8.1
  http: ^1.1.0
  provider: ^6.1.1
  avatar_glow: ^3.0.1
  speech_to_text: ^6.6.0
  flutter_keyboard_visibility: ^6.0.0
  table_calendar: ^3.1.0
  intl: ^0.19.0
  sse: ^4.1.4
  firebase_core: ^2.26.0
  firebase_messaging: ^14.7.18
  firebase_core_platform_interface: ^5.0.0
  web_socket_channel: ^2.4.0
  fluttertoast: ^8.2.4
  double_back_to_close: ^2.0.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
  fonts:
    - family: pretendard
      fonts:
        - asset: fonts/PretendardVariable.ttf
    - family: bronova
      fonts:
        - asset: fonts/BronovaBold.ttf
